(() => {
'use strict';
const D=window.HARAKA, KEY='haraka-data-v1';
const $=s=>document.querySelector(s), main=$('#main'), modal=$('#modal');
const latin=s=>String(s??'').replace(/[٠-٩۰-۹]/g,c=>String(c.charCodeAt(0)-(c>='۰'?1776:1632)));
const esc=s=>latin(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',moon:'<path d="M20 14a8 8 0 0 1-10-10 8 8 0 1 0 10 10Z"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',book:'<path d="M12 5v16M12 5Q7 2 2 4v15q5-2 10 2 5-4 10-2V4q-5-2-10 1Z"/>',history:'<path d="M4 8a9 9 0 1 1-1 7M4 3v5h5M12 7v5l3 2"/>',arrow:'<path d="m14 5-7 7 7 7M7 12h14"/>',check:'<path d="m5 12 4 4L19 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',play:'<path d="m8 4 12 8-12 8Z"/>',pause:'<path d="M8 5v14M16 5v14"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>',coffee:'<path d="M4 8h12v7a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5ZM16 8h2a3 3 0 0 1 0 6h-2M6 3v2m5-2v2"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.info}</svg>`;
const dateKey=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const parseDay=s=>new Date(s+'T12:00:00');
const arDate=s=>parseDay(s).toLocaleDateString('ar-SY-u-nu-latn',{weekday:'long',day:'numeric',month:'long'});
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const isMain=id=>['A','B','C'].includes(id);
const PLAN=Object.freeze({rounds:1,rest:45});
const defaults=()=>({schema:1,settings:{rounds:1,rest:45},history:[],active:null});
let state=defaults(),storageBroken=false,rawBroken=null,selected=dateKey(),view='today',lastFocus=null,toastTimeout;
const dayNames=['أحد','اثنين','ثلاثاء','أربعاء','خميس','جمعة','سبت'];
const validDate=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&!isNaN(parseDay(s))&&dateKey(parseDay(s))===s;
const finite=n=>typeof n==='number'&&Number.isFinite(n);
const recordVersion=r=>r.planVersion===undefined?1:r.planVersion;
const recordSequence=r=>D.sequence(r.session,r.rounds,recordVersion(r));
const itemName=i=>D.E[i.id].name+(i.side?` — ${i.side}`:'');
function validRecord(r){return r&&[1,2].includes(recordVersion(r))&&typeof r.id==='string'&&r.id.length<100&&D.sessions[r.session]&&validDate(r.date)&&[1,2].includes(r.rounds)&&Array.isArray(r.results)&&r.results.length===recordSequence(r).length&&r.results.every(v=>['done','skip'].includes(v))&&typeof r.note==='string'&&r.note.length<=2000&&['','comfortable','same','uncomfortable'].includes(r.feeling)&&finite(r.finishedAt)&&['finished','stopped'].includes(r.status);}
function validate(x){
 if(!x||x.schema!==1||!x.settings||![1,2].includes(x.settings.rounds)||![30,45,60,90].includes(x.settings.rest)||!Array.isArray(x.history)||x.history.length>10000||!x.history.every(validRecord))return false;
 if(new Set(x.history.map(r=>r.id)).size!==x.history.length)return false;
 const a=x.active;
 if(a!==null){if(!a||![1,2].includes(recordVersion(a))||typeof a.id!=='string'||a.id.length>100||!D.sessions[a.session]||!validDate(a.date)||![1,2].includes(a.rounds)||!Number.isInteger(a.cursor)||!finite(a.startedAt)||!Array.isArray(a.results)||a.results.length!==recordSequence(a).length||a.cursor<0||a.cursor>=a.results.length||!a.results.every((v,i)=>i<a.cursor?['done','skip'].includes(v):v===null)||!['exercise','rest'].includes(a.mode))return false;
 if(a.timer!==null&&(!a.timer||!finite(a.timer.remaining)||a.timer.remaining<0||a.timer.remaining>3600000||typeof a.timer.running!=='boolean'||!finite(a.timer.deadline)))return false;}
 return true;
}
function warn(text){const w=$('#storage-warning');w.hidden=false;w.textContent=text;}
try{const raw=localStorage.getItem(KEY);if(raw){const x=JSON.parse(raw);if(!validate(x))throw Error('invalid');state=x;}if(state.active?.timer){state.active.timer.running=false;state.active.timer.deadline=0;}}catch(e){storageBroken=true;try{rawBroken=localStorage.getItem(KEY)}catch{}warn('تعذّر قراءة الحفظ المحلي. لم نغيّر بياناتك السابقة. صدّر نسخة من الإعدادات قبل استعادة نسخة سليمة.');}
function save(){state.settings={...PLAN};if(storageBroken)return false;try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{warn('تعذّر حفظ التقدم على الجهاز. صدّر نسخة احتياطية الآن؛ قد يكون التخزين ممتلئًا أو محظورًا.');return false;}}
function toast(s){const t=$('#toast');t.textContent=s;t.hidden=false;clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>t.hidden=true,4200);}
function theme(){const dark=document.documentElement.dataset.theme==='dark';$('#theme-btn').innerHTML=icon(dark?'sun':'moon');$('#theme-btn').setAttribute('aria-label',dark?'تفعيل الوضع الفاتح':'تفعيل الوضع الداكن');}
$('#theme-btn').onclick=()=>{const t=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=t;try{localStorage.setItem('haraka-theme',t)}catch{}theme();};theme();
$('#settings-btn').innerHTML=icon('settings');$('#settings-btn').onclick=settings;
function navigate(to){view=to;location.hash=to;render();window.scrollTo({top:0,behavior:'instant'});main.focus({preventScroll:true});}
const tabs=[['today','home','اليوم'],['library','book','التمارين'],['history','history','سجلّي']];
tabs.forEach(([id,i,t])=>{const b=$(`[data-nav=${id}]`);b.innerHTML=icon(i)+t;b.onclick=()=>navigate(id);});
function showDialog(content){lastFocus=document.activeElement;$('#modal-content').innerHTML=content; if(!modal.open)modal.showModal();}
function closeDialog(){modal.close();if(lastFocus?.isConnected)lastFocus.focus();}
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
const modalHead=t=>`<div class="modal-head"><h2>${t}</h2><button class="icon-btn" data-action="close" aria-label="إغلاق">${icon('close')}</button></div>`;
function exerciseDetails(id){const e=D.E[id];if(!e)return;if(view==='session'){pauseTimer();renderPlayer();main.querySelector('[data-exercise]')?.focus();}showDialog(`${modalHead(e.name)}<img class="modal-image" src="${e.image}" alt="شرح أداء ${e.name}"><p class="small muted">استخدم المدى المريح لك.</p><p class="eyebrow" dir="ltr">${e.en}</p><ol>${e.steps.map(s=>`<li>${s}</li>`).join('')}</ol><details open><summary>انتبه</summary><p>${e.avoid}</p></details><details open><summary>نسخة أسهل</summary><p>${e.easier}</p></details>${e.photos?`<details class="photo-reference"><summary>صور مرجعية إضافية</summary>${e.photos.map((p,i)=>`<img src="${p}" alt="${e.name} — الوضعية ${i+1}" loading="lazy">`).join('')}<p>${e.photoCredit}</p></details>`:''}`);const illustration=$('#modal-content .modal-image');illustration.addEventListener('error',()=>{illustration.src=e.fallbackImage;},{once:true});}
function row(i){const e=D.E[i.id];return `<button class="exercise-row" aria-haspopup="dialog" data-exercise="${i.id}"><span class="row-text"><strong>${itemName(i)}</strong><small>${i.dose}</small></span><span class="row-help" aria-hidden="true">${icon('arrow')}</span></button>`;}
function workoutFor(date){return ({0:'A',2:'B',4:'C'})[parseDay(date).getDay()]||null;}
function weekDates(){const start=parseDay(selected);start.setDate(start.getDate()-start.getDay());return Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return dateKey(d);});}
function today(){
 const weeks=weekDates(),sid=workoutFor(selected),s=sid?D.sessions[sid]:null,a=state.active,isToday=selected===dateKey();
 const finished=state.history.filter(r=>isMain(r.session)&&r.status==='finished'&&!r.results.includes('skip')&&weeks.includes(r.date));

 const done=sid&&state.history.find(r=>r.date===selected&&r.session===sid&&r.status==='finished');
 const sameActive=a&&a.session===sid&&a.date===selected;
 const dayTitle=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'][parseDay(selected).getDay()];
 const saved=a&&!sameActive?`<section class="card saved-session"><div><span class="eyebrow">جلسة غير منتهية · ${arDate(a.date)}</span><h3>${D.sessions[a.session].title}</h3></div><button class="secondary" data-action="resume">أكمل الجلسة المحفوظة</button></section>`:'';
 main.innerHTML=`<div class="home-content"><h1 class="home-title">برنامجي اليومي</h1>
 <section class="weekly-calendar" aria-label="التقويم الأسبوعي"><div class="calendar-head"><button class="icon-btn" data-action="prev-week" aria-label="الأسبوع السابق">${icon('arrow')}</button><span>${parseDay(weeks[0]).toLocaleDateString('ar-SY-u-nu-latn',{day:'numeric',month:'short'})} — ${parseDay(weeks[6]).toLocaleDateString('ar-SY-u-nu-latn',{day:'numeric',month:'short',year:'numeric'})}</span><button class="icon-btn next-week" data-action="next-week" aria-label="الأسبوع التالي">${icon('arrow')}</button></div>${!isToday?'<button class="text-btn calendar-today" data-action="current-day">العودة لليوم</button>':''}
 <div class="week-strip" aria-label="أيام الأسبوع">${weeks.map((d,i)=>`<button class="day-button ${selected===d?'selected':''}" data-day="${d}" aria-pressed="${selected===d}" ${d===dateKey()?'aria-current="date"':''}><span>${dayNames[i]}</span><b>${parseDay(d).getDate()}</b><span class="day-marker">${finished.some(r=>r.date===d)?'✓ تم':workoutFor(d)?'تمرين':'راحة'}</span></button>`).join('')}</div>
 </section><div class="day-workout">
 ${s?`<section class="session-hero main-session" aria-label="جلسة اليوم المحدد"><span class="pill">${!isToday?'معاينة فقط':done?'جلسة منجزة':sameActive?'جلسة قيد التنفيذ':'جلسة اليوم'}</span><h2>جلسة ${dayTitle}: ${s.title}</h2><p class="eyebrow">${arDate(selected)}</p><div class="hero-meta"><span>${icon('clock')} حوالي 25 دقيقة</span><span>${sameActive?a.rounds:PLAN.rounds} جولة</span><span>راحة 45 ثانية</span></div>
 ${isToday?`<button class="primary" ${sameActive?'data-action="resume"':done?`data-edit="${esc(done.id)}"`:`data-start="${sid}"`}>${icon(sameActive?'play':done?'check':'play')} ${sameActive?'أكمل جلسة اليوم':done?'عرض الجلسة المنجزة':'ابدأ الجلسة'}</button>`:`<p class="start-help">هذه جلسة ${selected<dateKey()?'سابقة':'قادمة'} للمعاينة. بدء جلسة جديدة متاح في يومها فقط.</p>${done?`<button class="secondary" data-edit="${esc(done.id)}">عرض سجل هذه الجلسة</button>`:''}`}<details class="exercise-outline"><summary>تمارين هذه الجلسة</summary><div class="phase"><div class="phase-heading">التسخين</div>${D.warm.map(row).join('')}</div><div class="phase"><div class="phase-heading">التمارين الأساسية · 1 جولة</div>${(sameActive?recordSequence(a).filter(i=>i.phase==='التمارين'&&i.round===1):s.items).map(row).join('')}</div><div class="phase"><div class="phase-heading">التهدئة</div>${D.cool.map(row).join('')}</div></details></section>`:
 `<section class="card rest-day" aria-label="يوم راحة"><span class="pill">${isToday?'اليوم راحة':'يوم راحة · معاينة'}</span><h2>يوم راحة</h2><p class="eyebrow">${arDate(selected)}</p><p>حركات خفيفة إن أحببت.</p>${isToday?`<button class="secondary" data-start="mobility">${icon('play')} ابدأ الحركات الاختيارية</button>`:'<p class="plan-note">الحركات أدناه للمعاينة فقط.</p>'}<div class="optional-moves">${D.sessions.mobility.items.map(row).join('')}</div></section>`}
 ${saved}${sameActive&&!isToday?`<section class="card saved-session"><div><span class="eyebrow">بدأتها في ${arDate(a.date)}</span><h3>${D.sessions[a.session].title}</h3></div><button class="secondary" data-action="resume">أكمل الجلسة المحفوظة</button></section>`:''}
 </div></div>`;
}
function library(){main.innerHTML=`<div class="page-head"><div><h1>دليل الحركات</h1></div><span class="pill">${D.exercises.length.toLocaleString('en-US')} حركة</span></div><div class="library-grid">${D.exercises.map(e=>`<button class="exercise-card" aria-haspopup="dialog" data-exercise="${e.id}"><div class="exercise-caption"><span class="eyebrow">${e.area}</span><h3>${e.name}</h3><span class="row-help" aria-hidden="true">${icon('arrow')}</span></div></button>`).join('')}</div>`;}
function history(){const h=[...state.history].sort((a,b)=>b.finishedAt-a.finishedAt);main.innerHTML=`<div class="page-head"><div><span class="eyebrow">خطوة بخطوة</span><h1>سجلّي</h1></div><button class="secondary" data-action="export">${icon('download')} نسخة احتياطية</button></div>${h.length?`<p class="library-intro">${h.filter(r=>isMain(r.session)&&r.status==='finished').length.toLocaleString('en-US')} جلسات منتهية · ${h.filter(r=>!isMain(r.session)).length.toLocaleString('en-US')} استراحات حركة</p>${h.map(r=>`<article class="card record"><div class="record-main"><span class="record-date">${arDate(r.date)}</span><h3>${D.sessions[r.session].title}</h3><div class="summary-mini"><span>${r.status==='stopped'?'توقفت مبكرًا':r.results.includes('skip')?'انتهت مع تخطّي بعض الخطوات':'مكتملة'}</span><span>${r.results.filter(x=>x==='done').length.toLocaleString('en-US')} / ${r.results.length.toLocaleString('en-US')} خطوة</span><span>${({'comfortable':'حركة أريح','same':'نفس الشعور','uncomfortable':'انزعاج أكثر'})[r.feeling]||''}</span></div>${r.note?`<p style="margin-top:12px">${esc(r.note)}</p>`:''}</div><button class="icon-btn" data-edit="${esc(r.id)}" aria-label="تعديل ملاحظة الجلسة">${icon('book')}</button></article>`).join('')}`:`<div class="card empty">${icon('history')}<h2>رحلتك تبدأ من أول جلسة</h2><p>الجلسات والملاحظات ستظهر هنا، وتبقى محفوظة على هذا المتصفح.</p><button class="primary" data-action="home">عرض برنامجي</button></div>`}`;}
function start(id){if(!D.sessions[id])return;if(isMain(id)&&(selected!==dateKey()||workoutFor(dateKey())!==id)){toast('هذه معاينة فقط. اختر اليوم لتنفيذ جلسته المقررة.');return;}if(id==='mobility'&&(selected!==dateKey()||workoutFor(dateKey()))){toast('حركات يوم الراحة متاحة في يوم الراحة الحالي.');return;}if(storageBroken){toast('استعد نسخة سليمة من الإعدادات أولًا لحماية حفظك السابق.');return;}if(state.active){if(state.active.session===id){navigate('session');return;}showDialog(`${modalHead('لديك جلسة محفوظة')}<p>أكملها أو أنهِها مبكرًا قبل بدء جلسة أخرى.</p><div class="button-row" style="margin-top:20px"><button class="primary" data-action="resume-close">أكمل الجلسة</button><button class="secondary" data-action="stop-dialog">إنهاء مبكر</button></div>`);return;}
 const done=state.history.find(r=>r.date===dateKey()&&r.session===id&&r.status==='finished');if(id!=='break'&&done){editRecord(done.id);return;}
 const rounds=PLAN.rounds,seq=D.sequence(id,rounds);
 state.active={id:uid(),session:id,date:dateKey(),rounds,planVersion:D.version,cursor:0,results:seq.map(()=>null),mode:'exercise',timer:null,startedAt:Date.now()};initTimer();save();navigate('session');}
function initTimer(){const a=state.active;if(!a)return;const item=recordSequence(a)[a.cursor];a.timer=item.seconds?{remaining:item.seconds*1000,running:false,deadline:0}:null;}
let audioContext=null;
async function prepareSound(){
 try{
  const Audio=window.AudioContext||window.webkitAudioContext;
  if(!Audio)return false;
  if(!audioContext||audioContext.state==='closed')audioContext=new Audio();
  if(audioContext.state!=='running')await audioContext.resume();
  return audioContext.state==='running';
 }catch{return false;}
}
function ringTimer(){
 if(!audioContext||audioContext.state!=='running')return false;
 try{
  const now=audioContext.currentTime;
  [0,0.3,0.6].forEach((offset,index)=>{
   const tone=audioContext.createOscillator(),volume=audioContext.createGain();
   tone.type='sine';tone.frequency.value=index===2?880:660;
   volume.gain.setValueAtTime(0,now+offset);
   volume.gain.linearRampToValueAtTime(0.22,now+offset+0.02);
   volume.gain.exponentialRampToValueAtTime(0.001,now+offset+0.24);
   tone.connect(volume);volume.connect(audioContext.destination);
   tone.onended=()=>{tone.disconnect();volume.disconnect();};
   tone.start(now+offset);tone.stop(now+offset+0.25);
  });
  return true;
 }catch{return false;}
}
function remaining(){const t=state.active?.timer;return t?(t.running?Math.max(0,t.deadline-Date.now()):t.remaining):0;}
function pauseTimer(){const t=state.active?.timer;if(t?.running){t.remaining=remaining();t.running=false;t.deadline=0;save();}}
function toggleTimer(){const t=state.active?.timer;if(!t)return;if(t.running)pauseTimer();else if(t.remaining>0){t.running=true;t.deadline=Date.now()+t.remaining;save();}renderPlayer();}
const timeText=ms=>{const n=Math.ceil(ms/1000);return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;};
function renderPlayer(){const a=state.active;if(!a){navigate('today');return;}const seq=recordSequence(a),i=seq[a.cursor],e=D.E[i.id],p=Math.round(a.cursor/seq.length*100);
 main.innerHTML=`<div class="session-layout"><div class="player-head"><button class="text-btn" data-action="pause-home">${icon('pause')} حفظ وخروج</button><span class="small muted">${D.sessions[a.session].title}</span></div><div class="progress" role="progressbar" aria-label="تقدم الجلسة" aria-valuenow="${p}" aria-valuemin="0" aria-valuemax="100"><span style="width:${p}%"></span></div>${a.mode==='rest'?`<section class="card rest-panel"><span class="pill">استراحة</span><h2 style="margin-top:18px">خذ نفسًا، على مهلك</h2><p>يمكنك تمديد الراحة قبل الحركة التالية.</p><div class="timer-value" id="timer">${timeText(remaining())}</div><div class="timer-controls"><button class="secondary" data-action="timer">${icon(a.timer.running?'pause':'play')} ${a.timer.running?'إيقاف مؤقت':'تشغيل'}</button><button class="secondary" data-action="extend">+ 15 ثانية</button></div><div class="next-preview"><span class="eyebrow">التالي · ${i.phase}${i.round?' · الجولة '+i.round:''}</span><h3>${itemName(i)}</h3><span class="small muted">${i.dose}</span></div><button class="primary full" data-action="end-rest">جاهز، انتقل للتمرين ${icon('arrow')}</button></section>`:`<section class="card player-card"><div class="player-body"><span class="eyebrow">${i.phase}${i.round&&isMain(a.session)?` · الجولة ${i.round} من ${a.rounds}`:''} · الخطوة ${a.cursor+1} من ${seq.length}</span><h1>${itemName(i)}</h1><button class="secondary performance-help" data-exercise="${e.id}">${icon('info')} طريقة الأداء</button><div class="dose"><div><small>الهدف المريح</small><strong>${i.dose}</strong></div><span class="pill">بدون استعجال</span></div>${i.id==='side-plank'&&!i.side?'<p class="small muted">المؤقّت للجهتين: بدّل الجانب عند 10 ثوانٍ، وأوقفه مؤقتًا أثناء الانتقال.</p>':''}${i.id==='chest'&&i.seconds===40?'<p class="small muted">أرخِ الذراعين لحظة بين المرتين.</p>':''}${i.seconds?`<div class="timer-value" id="timer">${timeText(remaining())}</div><div class="timer-controls"><button class="secondary" data-action="timer">${icon(a.timer?.running?'pause':'play')} ${a.timer?.running?'إيقاف المؤقّت':'ابدأ المؤقّت'}</button><button class="text-btn" data-action="reset-timer">إعادة الوقت</button></div>`:''}<div class="player-actions"><button class="primary" data-action="done">${icon('check')} ${i.phase==='التمارين'?'أنهيت المجموعة':'أنهيت الخطوة'}</button><button class="text-btn" data-action="skip">تخطّي</button></div><p class="small muted" style="margin-top:12px">إذا زاد الانزعاج، توقف. يمكنك إنهاء الخطوة قبل العدد أو الوقت المستهدف.</p></div></section>`}<div class="button-row" style="margin-top:14px"><button class="text-btn" data-action="stop">إنهاء الجلسة مبكرًا</button></div></div>`;
}
function advance(result){const a=state.active;if(!a||a.mode!=='exercise')return;pauseTimer();const seq=recordSequence(a),previous=seq[a.cursor];a.results[a.cursor]=result;a.cursor++;
 if(a.cursor>=seq.length){finish('finished');return;}
 const next=seq[a.cursor];if(previous.phase==='التمارين'&&next.phase==='التمارين'){a.mode='rest';a.timer={remaining:PLAN.rest*1000,running:true,deadline:Date.now()+PLAN.rest*1000};}else{a.mode='exercise';initTimer();}save();renderPlayer();}
function finish(status){const a=state.active;if(!a)return;pauseTimer();const r={id:a.id,session:a.session,date:a.date,rounds:a.rounds,planVersion:recordVersion(a),results:a.results.map(v=>v||'skip'),status,note:'',feeling:'',finishedAt:Date.now()};if(!state.history.some(x=>x.id===r.id))state.history.push(r);state.active=null;save();view='summary';location.hash='summary';summary(r);}
function summary(r){$('.bottom-nav').hidden=false;main.innerHTML=`<div class="session-layout"><section class="card"><div class="completion"><span class="complete-mark">${icon('check')}</span><span class="eyebrow">${arDate(r.date)}</span><h1>${r.status==='finished'?'انتهت جلستك':'أخذت ما يناسبك اليوم'}</h1><p>${D.sessions[r.session].title} · ${r.results.filter(x=>x==='done').length.toLocaleString('en-US')} خطوات منفّذة</p></div>${noteForm(r)}<button class="primary full" data-save-note="${r.id}">احفظ الملاحظة واعرض السجل</button><p class="small muted" style="margin-top:14px">تم حفظ الجلسة. إضافة الملاحظة اختيارية.</p></section></div>`;}
function noteForm(r){return `<fieldset style="border:0;padding:0;margin:0"><legend style="font-weight:700;margin-bottom:12px">كيف شعرت بعد الحركة؟</legend><div class="feelings">${[['comfortable','أريح'],['same','نفس الشعور'],['uncomfortable','انزعاج أكثر']].map(([v,t])=>`<label class="secondary"><input type="radio" name="feeling" value="${v}" ${r.feeling===v?'checked':''}><span>${t}</span></label>`).join('')}</div></fieldset><div class="form-field"><label for="session-note">ملاحظة لنفسك <span class="muted">(اختيارية)</span></label><textarea id="session-note" maxlength="2000" placeholder="أي حركة كانت مريحة؟ وأي تمرين يحتاج تخفيفًا؟">${esc(r.note)}</textarea></div>`;}
function editRecord(id){const r=state.history.find(x=>x.id===id);if(!r)return;showDialog(`${modalHead(D.sessions[r.session].title)}<p class="eyebrow">${arDate(r.date)}</p>${noteForm(r)}<button class="primary full" data-save-note="${esc(id)}">حفظ الملاحظة</button>`);}
function saveNote(id){const r=state.history.find(x=>x.id===id);if(!r)return;const root=modal.open?modal:main;r.note=root.querySelector('#session-note').value.trim();r.feeling=root.querySelector('[name=feeling]:checked')?.value||'';save();if(modal.open)closeDialog();navigate('history');toast(r.feeling==='uncomfortable'?'خفف الحركة المزعجة أو تجاوزها في المرة القادمة.':'تم حفظ الملاحظة');}
function stopPrompt(){pauseTimer();showDialog(`${modalHead('إنهاء الجلسة مبكرًا؟')}<p>سنحفظ ما نفّذته ونضع بقية الخطوات كمتخطّاة. لن تُحسب كجلسة مكتملة.</p><div class="button-row" style="margin-top:20px"><button class="secondary" data-action="close">متابعة الجلسة</button><button class="primary" data-action="confirm-stop">إنهاء وحفظ</button></div>`);}
function guide(){showDialog(`${modalHead('قواعد البرنامج')}<p>الهدف حركة أريح وتخفيف تيبّس الجلوس. الشدة خفيفة إلى متوسطة، مع بقاء القدرة على الكلام والتنفس براحة.</p><ul class="note-list"><li>الأحد والثلاثاء والخميس. يوم راحة بين الجلسات.</li><li>الخطة الحالية ثابتة على 1 جولة مع راحة 45 ثانية بين التمارين الأساسية.</li><li>لا توجد زيادة تلقائية أو خيارات لتغيير عدد الجولات. إذا احتجت تعديل البرنامج لاحقًا، راجع الخطة أولًا.</li><li>لا تحبس النفس. خذ راحة أطول عندما تحتاجها.</li><li>الألم المتزايد ليس هدفًا للتمرين. توقف عن الحركة التي تزيده.</li><li>إذا استمر الألم لأسابيع أو ظهر تنميل أو ضعف، اطلب تقييمًا من مختص؛ السبب لا يُحسم من الجلوس وحده.</li><li>إذا كانت الحركات جديدة عليك، يمكن لمدرّب مؤهل أو شخص بالغ موثوق مساعدتك على التأكد من الوضعية.</li></ul><div class="setting-block"><h3>فواصل اللابتوب</h3><p>كل 45–60 دقيقة تقريبًا، قم لدقيقتين. هذا تذكير عملي لتغيير الوضعية، وليس توقيتًا علاجيًا إلزاميًا. لا يرسل الموقع إشعارات بالخلفية.</p></div><p class="credits">مراجع عامة: <a href="https://www.nhs.uk/symptoms/neck-pain-and-stiff-neck/" target="_blank" rel="noopener noreferrer">NHS — ألم الرقبة</a> · <a href="https://www.nhs.uk/conditions/back-pain/" target="_blank" rel="noopener noreferrer">NHS — ألم الظهر</a>. البرنامج مرجع حركة عام ولا يشخّص سبب الألم.</p>`);}
function settings(){const weeks=weekDates();const count=new Set(state.history.filter(r=>isMain(r.session)&&r.status==='finished'&&!r.results.includes('skip')&&weeks.includes(r.date)).map(r=>r.date)).size;showDialog(`${modalHead('الحفظ والمساعدة')}<div class="setting-block"><h3>إنجاز الأسبوع المعروض</h3><p>${arDate(weeks[0])} — ${arDate(weeks[6])}</p><strong><bdi>${count} / 3</bdi> جلسات</strong></div><p class="plan-note">الخطة ثابتة: 1 جولة و45 ثانية راحة بين التمارين الأساسية. يمكنك إيقاف المؤقّت أو أخذ وقت إضافي عند الحاجة دون تغيير الخطة.</p><div class="setting-block"><h3>بياناتك على هذا الجهاز</h3><p>لا يوجد حساب أو مزامنة. استخدم نفس المتصفح ونفس رابط الموقع، وتجنب التصفح الخفي. احتفظ بنسخة احتياطية دوريًا.</p><div class="button-row"><button class="secondary" data-action="export">${icon('download')} تصدير نسخة</button><button class="secondary" data-action="import">استيراد نسخة</button></div></div><div class="setting-block"><h3>تنبيه المؤقّت</h3><button class="secondary" data-action="test-sound">تجربة الرنّة</button><p>ارفع صوت الوسائط. يعمل التنبيه أثناء بقاء الصفحة مفتوحة.</p></div><div class="setting-block"><h3>اختصار على الموبايل</h3><p>من قائمة المتصفح اختر «إضافة إلى الشاشة الرئيسية» للوصول السريع إلى برنامجك.</p></div><div class="button-row"><button class="text-btn" data-action="guide">قواعد البرنامج</button><button class="text-btn" data-action="credits">مصادر الصور</button></div>`);}
function credits(){showDialog(`${modalHead('الصور والمراجع')}<p class="credits">صور الشرح الأساسية تُضاف بصيغة JPG بواسطة صاحب الموقع. مخططات SVG الأصلية المرفقة تظهر بديلًا عند تعذّر تحميل الصورة. نسب المصادر أدناه تخص الصور المرجعية الإضافية فقط.</p><div class="setting-block"><h3>الصور المرجعية الإضافية</h3><p>صور القرفصاء والجسر وتحريك الظهر من Free Exercise DB، المنشورة تحت Unlicense بحسب مستودع المصدر. الصور محفوظة ضمن المشروع دون تعديل محتواها.</p><a href="https://github.com/yuhonas/free-exercise-db" target="_blank" rel="noopener noreferrer">المصدر والترخيص</a></div><p class="credits">رسم لفّ الكتفين: Cancer Research UK / Wikimedia Commons، <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>، دون تعديل. <a href="https://commons.wikimedia.org/wiki/File:Diagram_showing_how_to_do_shoulder_rolls_after_breast_reconstruction_surgery_CRUK_151.svg" target="_blank" rel="noopener noreferrer">صفحة المصدر</a>.</p><p class="credits">قائمة الملفات وروابطها وتراخيصها متوفرة في ASSET-CREDITS.md ضمن المشروع.</p>`);}
let backupUrl=null;
function download(name,content){if(backupUrl)URL.revokeObjectURL(backupUrl);backupUrl=URL.createObjectURL(new Blob([content],{type:'application/json'}));showDialog(`${modalHead('نسختك الاحتياطية جاهزة')}<p class="plan-note">احفظ الملف في مكان آمن. إذا لم يسمح المتصفح بالتنزيل، انسخ النص واحتفظ به في ملف بامتداد .json.</p><a class="primary full" href="${backupUrl}" download="${name}">${icon('download')} تنزيل ملف JSON</a><details style="margin-top:18px"><summary>نسخ البيانات كنص</summary><div class="form-field"><label for="backup-text">بيانات النسخة</label><textarea id="backup-text" readonly dir="ltr">${esc(content)}</textarea><button class="secondary" data-action="copy-backup">نسخ النص</button></div></details>${pendingImport?'<button class="secondary full" style="margin-top:14px" data-action="confirm-import">استبدال البيانات بالنسخة المستوردة</button>':''}`);}
function exportData(){pauseTimer();if(rawBroken!==null){download(`haraka-recovery-${dateKey()}.json`,rawBroken);return;}download(`haraka-backup-${dateKey()}.json`,JSON.stringify({app:'haraka',exportedAt:new Date().toISOString(),data:state},null,2));}
let pendingImport=null;
$('#import-file').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>8*1024*1024)throw Error();const x=JSON.parse(await f.text());if(x.app!=='haraka'||!validate(x.data))throw Error();pendingImport=x.data;pendingImport.settings={...PLAN};if(pendingImport.active?.timer){pendingImport.active.timer.running=false;pendingImport.active.timer.deadline=0;}showDialog(`${modalHead('استعادة النسخة الاحتياطية')}<p>النسخة تحتوي على ${pendingImport.history.length.toLocaleString('en-US')} سجل${pendingImport.active?' وجلسة غير منتهية':''}. ستستبدل البيانات الحالية على هذا الجهاز.</p><p class="plan-note">صدّر بياناتك الحالية أولًا إذا أردت الاحتفاظ بها.</p><div class="button-row"><button class="secondary" data-action="export">تصدير الحالي</button><button class="primary" data-action="confirm-import">استبدال واستعادة</button></div>`);}catch{toast('الملف غير صالح أو من إصدار غير مدعوم. لم تتغير بياناتك.');}};
function render(){$('.bottom-nav').hidden=view==='session';document.querySelectorAll('[data-nav]').forEach(b=>{b.classList.toggle('active',b.dataset.nav===view);b.setAttribute('aria-current',b.dataset.nav===view?'page':'false');});if(view==='session')renderPlayer();else if(view==='library')library();else if(view==='history')history();else{view='today';today();}}
function actions(event){const t=event.target.closest('button');if(!t)return;if(t.dataset.start||['timer','done','skip','resume','resume-close','extend'].includes(t.dataset.action))void prepareSound();if(t.dataset.exercise){exerciseDetails(t.dataset.exercise);return;}if(t.dataset.day){selected=t.dataset.day;today();return;}if(t.dataset.start){start(t.dataset.start);return;}if(t.dataset.edit){editRecord(t.dataset.edit);return;}if(t.dataset.saveNote){saveNote(t.dataset.saveNote);return;}
 switch(t.dataset.action){case 'test-sound':void prepareSound().then(ok=>{if(!ok||!ringTimer())toast('تعذّر تشغيل الصوت في هذا المتصفح.');});break;case 'prev-week':case 'next-week':{const d=parseDay(selected);d.setDate(d.getDate()+(t.dataset.action==='prev-week'?-7:7));selected=dateKey(d);today();break;}case 'current-day':selected=dateKey();today();break;case 'close':closeDialog();break;case 'home':navigate('today');break;case 'resume':navigate('session');break;case 'resume-close':closeDialog();navigate('session');break;case 'pause-home':pauseTimer();navigate('today');toast('حُفظت الخطوات. يمكنك المتابعة لاحقًا.');break;case 'done':advance('done');break;case 'skip':advance('skip');break;case 'timer':toggleTimer();break;case 'reset-timer':pauseTimer();initTimer();save();renderPlayer();break;case 'extend':{const a=state.active;if(!a?.timer)break;const n=remaining()+15000;a.timer.remaining=n;if(a.timer.running)a.timer.deadline=Date.now()+n;save();renderPlayer();break;}case 'end-rest':if(state.active){state.active.mode='exercise';initTimer();save();renderPlayer();}break;case 'stop':case 'stop-dialog':stopPrompt();break;case 'confirm-stop':closeDialog();finish('stopped');break;case 'guide':guide();break;case 'credits':credits();break;case 'copy-backup':{const field=$('#backup-text');field.focus();field.select();if(navigator.clipboard?.writeText)navigator.clipboard.writeText(field.value).then(()=>toast('تم نسخ بيانات النسخة')).catch(()=>toast('تم تحديد النص؛ اختر نسخ من قائمة المتصفح.'));else toast('تم تحديد النص؛ اختر نسخ من قائمة المتصفح.');break;}case 'export':exportData();break;case 'import':$('#import-file').click();break;case 'confirm-import':if(pendingImport){try{localStorage.setItem(KEY,JSON.stringify(pendingImport));state=pendingImport;pendingImport=null;storageBroken=false;rawBroken=null;$('#storage-warning').hidden=true;closeDialog();navigate('today');toast('تمت استعادة النسخة');}catch{toast('تعذّر الحفظ؛ لم نستبدل البيانات الحالية.');}}break;}
}
document.addEventListener('click',actions);
setInterval(()=>{const t=state.active?.timer;if(!t?.running)return;const ms=remaining();const node=$('#timer');if(node)node.textContent=timeText(ms);if(ms<=0){ringTimer();t.remaining=0;t.running=false;t.deadline=0;save();if(view==='session'){renderPlayer();toast(state.active.mode==='rest'?'انتهت الراحة؛ انتقل عندما تكون جاهزًا.':'انتهى الوقت؛ أكّد إنجاز الخطوة عندما تكون جاهزًا.');}}},200);
let observedDay=dateKey();
document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseTimer();else{const now=dateKey();if(now!==observedDay){if(selected===observedDay)selected=now;observedDay=now;}if(view==='session')renderPlayer();else if(view==='today')today();}});window.addEventListener('pagehide',pauseTimer);
window.addEventListener('storage',e=>{if(e.key===KEY){try{const x=JSON.parse(e.newValue);if(validate(x)){state=x;state.settings={...PLAN};if(state.active?.timer)state.active.timer.running=false;render();toast('تحدّث السجل من نافذة أخرى.');}}catch{}}});
window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(['today','library','history','session'].includes(v)){view=v;render();}});
const initial=location.hash.slice(1);if(['today','library','history','session'].includes(initial))view=initial;render();
})();
